
<li class="office-list"><a href="[field:typelink /]"> <i class="fa fa-angle-double-right"></i>[field:typename/]</a> 
         <div class="office-detail  hide">
          <h1><a href="/Index/read/id/56.html">[field:typename/]</a></h1> 
          <p><font face="Arial, Tahoma, Helvetica Neue, Luxi Sans, DejaVu Sans, Hiragino Sans GB, STHeiti, Microsoft YaHei, Arial, sans-serif"> [field:description /]</font><br /></p>
         </div> </li>
