<?php
$z[0]=Array("field","",85,107);
$z[0][4]['name']="typename";
$z[1]=Array("channel","\r\n<li class=\"office-list\"><a href=\"[field:typelink /]\"> <i class=\"fa fa-angle-double-right\"></i>[field:typename/]</a> \r\n         <div class=\"office-detail  hide\">\r\n          <h1><a href=\"/Index/read/id/56.html\">[field:typename/]</a></h1> \r\n          <p><font face=\"Arial, Tahoma, Helvetica Neue, Luxi Sans, DejaVu Sans, Hiragino Sans GB, STHeiti, Microsoft YaHei, Arial, sans-serif\"> [field:description /]</font><br /></p>\r\n         </div> </li>\r\n",194,705);
$z[1][4]['type']="son";
$z[1][4]['typeid']="";
$z[1][4]['noself']="true";
$z[2]=Array("field","",773,793);
$z[2][4]['name']="arcpic";

?>