<?php
$z[0]=Array("field","",41,62);
$z[0][4]['name']="typedir";
$z[1]=Array("field","",64,86);
$z[1][4]['name']="typename";
$z[2]=Array("arclist","\r\n<time>[field:stime/]</time>\r\n     <h5> <a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:title/]\">[field:title function=\"cn_substr(@me,140)\"/]</a></h5>\r\n",215,482);
$z[2][4]['typeid']="";
$z[2][4]['att']="";
$z[2][4]['limit']="0,2";
$z[2][4]['titlelen']="120";
$z[2][4]['infolen']="";
$z[2][4]['orderby']="pubdate";

?>