<?php
$z[0]=Array("field","",321,343);
$z[0][4]['name']="typename";
$z[1]=Array("arclist","\r\n<li><a href=\"[field:arcurl/]\" target=\"\"><i class=\"fa fa-angle-double-right\"></i><h5>[field:title function=\"cn_substr(@me,140)\"/]</h5><time>[field:stime/]</time></a></li>\r\n",406,685);
$z[1][4]['typeid']="";
$z[1][4]['att']="";
$z[1][4]['limit']="0,5";
$z[1][4]['titlelen']="120";
$z[1][4]['infolen']="";
$z[1][4]['orderby']="pubdate";

?>