{dede:field name='keywords'}商务部,配额{/dede:field}
{dede:field name='description'}据商务部12月30日消息，商务部公布2016年钨、锑、白银出口国营贸易企业名单以及2016年铟、锡、磷矿石出口企业名单，下达锑、白银、铟{/dede:field}
{dede:field name='title'}商务部公布2016年第一批工业品出口配额 占比超70%{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}<p><span style="font-family: '';">&#160; &#160; 据商务部12月30日消息，商务部公布2016年钨、锑、白银出口国营贸易企业名单以及2016年铟、锡、磷矿石出口企业名单，下达锑、白银、铟、锡、磷矿石2016年第一批出口配额。</span></p>
<p>　　此次下达的配额量为年度配额总量的70-71%。2016年第一批出口配额主要参照各企业近三年的产量、出口数量、出口金额进行计算。&#160;</p>{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
