<?php
$z[0]=Array("global","\$a=\"left\"; \$b=\"right\";if (@me==1) @me=\$a; else @me=\$b;",17,126);
$z[0][4]['name']="itemindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("field","",348,370);
$z[1][4]['name']="typename";
$z[2]=Array("arclist","\r\n<li><a href=\"[field:arcurl/]\" target=\"\"><i class=\"fa fa-angle-double-right\"></i><h5>[field:title function=\"cn_substr(@me,140)\"/]</h5><time>[field:stime/]</time></a></li>\r\n",433,712);
$z[2][4]['typeid']="";
$z[2][4]['att']="";
$z[2][4]['limit']="0,5";
$z[2][4]['titlelen']="120";
$z[2][4]['infolen']="";
$z[2][4]['orderby']="pubdate";

?>