<?php
$z[0]=Array("item","",4,90);
$z[0][4]['name']="系统基本参数";
$z[0][4]['link']="sys_info.php";
$z[0][4]['rank']="sys_Edit";
$z[0][4]['target']="main";
$z[1]=Array("item","",94,186);
$z[1][4]['name']="系统用户管理";
$z[1][4]['link']="sys_admin_user.php";
$z[1][4]['rank']="sys_User";
$z[1][4]['target']="main";
$z[2]=Array("item","",190,280);
$z[2][4]['name']="数据库备份/还原";
$z[2][4]['link']="sys_data.php";
$z[2][4]['rank']="sys_Data";
$z[2][4]['target']="main";

?>