<?php
$z[0]=Array("sppage","",0,73);
$z[0][4]['sptype']="full";
$z[0][4]['srul']="1";
$z[0][4]['erul']="5";
$z[1]=Array("previewurl","http://business.sohu.com/20160412/n443926105.shtml",75,160);
$z[2]=Array("keywordtrim","",162,199);
$z[3]=Array("descriptiontrim","",201,246);
$z[4]=Array("item","\r\n   {dede:match}<h1 itemprop=\"headline\">[内容]</h1>{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",248,424);
$z[4][4]['field']="title";
$z[4][4]['value']="";
$z[4][4]['isunit']="";
$z[4][4]['isdown']="";
$z[5]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",426,566);
$z[5][4]['field']="writer";
$z[5][4]['value']="";
$z[5][4]['isunit']="";
$z[5][4]['isdown']="";
$z[6]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",568,708);
$z[6][4]['field']="source";
$z[6][4]['value']="";
$z[6][4]['isunit']="";
$z[6][4]['isdown']="";
$z[7]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}@me=GetMkTime(@me);{/dede:function}\r\n",710,870);
$z[7][4]['field']="pubdate";
$z[7][4]['value']="";
$z[7][4]['isunit']="";
$z[7][4]['isdown']="";
$z[8]=Array("item","\r\n   {dede:match}<div itemprop=\"articleBody\">[内容]<!-- seo标签描述 -->{/dede:match}\r\n   {dede:trim replace=''}<a([^>]*)>(.*)</a>{/dede:trim}\r\n{dede:trim replace=''}<script([^>]*)>(.*)</script>{/dede:trim}\r\n{dede:trim replace=''}<!--(.*)-->{/dede:trim}\r\n{dede:trim replace=''}<table([^>]*)>(.*)</table>{/dede:trim}\r\n{dede:trim replace=''}<style([^>]*)>(.*)</style>{/dede:trim}\r\n{dede:trim replace=''}<img([^>]*)>{/dede:trim}\r\n{dede:trim replace=''}<object([^>]*)>(.*)</object>{/dede:trim}\r\n{dede:trim replace=''}<embed([^>]*)>(.*)</embed>{/dede:trim}\r\n{dede:trim replace=''}<iframe([^>]*)>(.*)</iframe>{/dede:trim}\r\n{dede:trim replace=''}<param([^>]*)>(.*)</param>{/dede:trim}\r\n{dede:trim replace=''}<div([^.]*)>{/dede:trim}\r\n{dede:trim replace=''}</div>{/dede:trim}\r\n   {dede:function}{/dede:function}\r\n",872,1749);
$z[8][4]['field']="body";
$z[8][4]['value']="";
$z[8][4]['isunit']="1";
$z[8][4]['isdown']="1";

?>