<?php
$z[0]=Array("channelartlist","\r\n<dl>\r\n       {dede:field.typename/} \r\n      \r\n	  {dede:channel type='son' typeid=''}\r\n<a href=\"[field:typelink /]\">\r\n       <dd>\r\n        <i class=\"fa fa-angle-double-right\"></i>[field:typename/]\r\n       </dd></a>\r\n{/dede:channel} \r\n     </dl>\r\n",73,396);
$z[0][4]['typeid']="41,47,52,56,58,62,66,74";
$z[1]=Array("sql","[field:content/]",458,547);
$z[1][4]['sql']="Select * from dede_addon_suipian where aid=37";

?>