<?php
$z[0]=Array("sql","[field:content/]",100,189);
$z[0][4]['sql']="Select * from dede_addon_suipian where aid=36";
$z[1]=Array("sql","[field:litpic/]",634,715);
$z[1][4]['sql']="Select * from dede_archives where id=1";
$z[2]=Array("channelartlist","\r\n<li class=\"nav-bar-item nav-bar-office\"> <a href=\"javascript:void(0);\" class=\"nav01\">{dede:field.typename/}</a> \r\n      <div class=\"item item-office\"> \r\n       <ul class=\"office\"> \r\n        \r\n		{dede:channel type='son' typeid='' noself='true'}\r\n<li class=\"office-list\"><a href=\"[field:typelink /]\"> <i class=\"fa fa-angle-double-right\"></i>[field:typename/]</a> \r\n         <div class=\"office-detail  hide\">\r\n          <h1><a href=\"/Index/read/id/56.html\">[field:typename/]</a></h1> \r\n          <p><font face=\"Arial, Tahoma, Helvetica Neue, Luxi Sans, DejaVu Sans, Hiragino Sans GB, STHeiti, Microsoft YaHei, Arial, sans-serif\"> [field:description /]</font><br /></p>\r\n         </div> </li>\r\n{/dede:channel}\r\n         \r\n        <div class=\"nav-item-img\">\r\n         <img src=\"{dede:field.arcpic/}\" alt=\"\" />\r\n        </div> \r\n       </ul> \r\n      </div> </li>\r\n",777,1713);
$z[2][4]['typeid']="41,47,52,56,58,62,66,74";

?>