<?php
$z[0]=Array("field","",104,123);
$z[0][4]['name']="title";
$z[1]=Array("global","",124,150);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",194,221);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("global","",264,294);
$z[3][4]['name']="cfg_description";
$z[4]=Array("include","",824,860);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",996,1018);
$z[5][4]['name']="typename";
$z[6]=Array("field","",1131,1160);
$z[6][4]['name']="position";
$z[7]=Array("list","\r\n<li><i class=\"fa fa-angle-double-right\"></i> \r\n        <div class=\"nt-cont\"> \r\n         <a href=\"[field:arcurl/]\" title=\"[field:title/]\" target=\"_blank\">[field:title/]</a> \r\n        </div> \r\n        <div class=\"nt-time\">\r\n         [field:pubdate function=\"GetDateMK(@me)\"/]\r\n        </div> </li>\r\n",1275,1637);
$z[7][4]['pagesize']="20";
$z[7][4]['titlelen']="120";
$z[7][4]['infolen']="";
$z[8]=Array("pagelist","",1829,1907);
$z[8][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",2059,2100);
$z[9][4]['filename']="rightside.htm";
$z[10]=Array("include","",2115,2153);
$z[10][4]['filename']="footer.htm";

?>